ALTER TABLE event_types
  ADD COLUMN IF NOT EXISTS color TEXT NOT NULL DEFAULT '#2563eb';

ALTER TABLE event_types
  ADD COLUMN IF NOT EXISTS notice_minimum_hours INTEGER NOT NULL DEFAULT 0;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS email_sent_host BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS email_sent_invitee BOOLEAN NOT NULL DEFAULT FALSE;
